### ISSUE TITLE
Links are not clickable links

### ISSUE THREAD

**Issue by smerchek** [dustyburwell/jell#1]
When a person types a link in their message, this link is not clickable. Instead, one must highlight->copy->paste to open the link.

**Comment by dustyburwell** [comment]
Could you elaborate, because that's simply not true. Do you have an example of text that did not result in a clickable link? Is the text blue and underlined and clicking it doesn't do anything, or is it simply plain text?

**Comment by smerchek** [comment]
Hmm.. Ok, it was a link that had lots of escaped characters in it. It was
not blue at all. I should've put the link in issue. I'll do that tomorrow
when I'm back at my workstation.
- Scott

Sent from my iPhone

On Sep 26, 2012, at 6:39 PM, Dusty Burwell notifications@github.com wrote:

Could you elaborate, because that's simply not true. Do you have an example
of text that did not result in a clickable link? Is the text blue and
underlined and clicking it doesn't do anything, or is it simply plain text?

—
Reply to this email directly or view it on
GitHubhttps://github.com/dustyburwell/jell/issues/1#issuecomment-8911194.

**Comment by smerchek** [comment]
Here is the link in question:
http://youtrack/issues?q=%23illum+%23Completed+%23Verified+%23Fixed+Fix+versions%3A+%7BNo+Fix+versions%7D+

**Comment by smerchek** [comment]
Further testing: 
- http://www.google.com works
- www.google.com does not work
- http://youtrack/ does not work

It appears that the real issue is that a link to an internal server (one without TLD suffix) is not recognized as a link.

**Comment by dustyburwell** [comment]
Oic... Makes sense. I'll probably change the regex so it's simpler.

How's this sound? How about anything that starts with HTTP: or starts with W WW. should get highlighted up until a space. I also think that  if it starts with a // it should be highlighted.

**Comment by smerchek** [comment]
Sounds good to me.
- Scott

**Comment by dustyburwell** [comment]
That last commit fixes the original issue, but does not address linkifying things that start with '\'. That's apparently more than my tired brain can deal with right now.

**Comment by dustyburwell** [comment]
I've lost interest in getting UNC paths working. They're annoying and not part of the original issue. If anyone else ever has an issue with it, they can feel free to create a new issue.
