### ISSUE TITLE
Room topics are not displayed

### ISSUE THREAD

**Issue by adunkman** [dustyburwell/jell#3]
There is no display for room topics.

**Comment by dustyburwell** [comment]
There's actually a place to put these under the room title... it's just not being set.

**Comment by AdmiralNemo** [comment]
Hope this gets fixed soon, otherwise, how will we know when lunch is?

**Comment by adunkman** [comment]
🚮

**Comment by dustyburwell** [comment]
You sure you don't want this one fixed?

**Comment by adunkman** [comment]
I mean, if you have the time! 

![stair-climbing](https://user-images.githubusercontent.com/14930/40181513-3ffd2ebc-59b7-11e8-943b-b4d0ead0f7df.gif)
